export interface Country {
    code: string;
    dial: string;
    name: string;
    flag: string;
}

export const COUNTRIES: Country[] = [
    // Highlighted / Default
    { code: 'ng', dial: '+234', name: 'Nigeria', flag: 'https://flagcdn.com/w20/ng.png' },
    { code: 'us', dial: '+1', name: 'United States', flag: 'https://flagcdn.com/w20/us.png' },
    { code: 'gb', dial: '+44', name: 'United Kingdom', flag: 'https://flagcdn.com/w20/gb.png' },
    { code: 'za', dial: '+27', name: 'South Africa', flag: 'https://flagcdn.com/w20/za.png' },
    { code: 'ke', dial: '+254', name: 'Kenya', flag: 'https://flagcdn.com/w20/ke.png' },
    { code: 'gh', dial: '+233', name: 'Ghana', flag: 'https://flagcdn.com/w20/gh.png' },
    { code: 'ca', dial: '+1', name: 'Canada', flag: 'https://flagcdn.com/w20/ca.png' },
    { code: 'au', dial: '+61', name: 'Australia', flag: 'https://flagcdn.com/w20/au.png' },

    // Ordered alphabetically
    { code: 'af', dial: '+93', name: 'Afghanistan', flag: 'https://flagcdn.com/w20/af.png' },
    { code: 'al', dial: '+355', name: 'Albania', flag: 'https://flagcdn.com/w20/al.png' },
    { code: 'dz', dial: '+213', name: 'Algeria', flag: 'https://flagcdn.com/w20/dz.png' },
    { code: 'ad', dial: '+376', name: 'Andorra', flag: 'https://flagcdn.com/w20/ad.png' },
    { code: 'ao', dial: '+244', name: 'Angola', flag: 'https://flagcdn.com/w20/ao.png' },
    { code: 'ag', dial: '+1', name: 'Antigua and Barbuda', flag: 'https://flagcdn.com/w20/ag.png' },
    { code: 'ar', dial: '+54', name: 'Argentina', flag: 'https://flagcdn.com/w20/ar.png' },
    { code: 'am', dial: '+374', name: 'Armenia', flag: 'https://flagcdn.com/w20/am.png' },
    { code: 'at', dial: '+43', name: 'Austria', flag: 'https://flagcdn.com/w20/at.png' },
    { code: 'az', dial: '+994', name: 'Azerbaijan', flag: 'https://flagcdn.com/w20/az.png' },
    { code: 'bs', dial: '+1', name: 'Bahamas', flag: 'https://flagcdn.com/w20/bs.png' },
    { code: 'bh', dial: '+973', name: 'Bahrain', flag: 'https://flagcdn.com/w20/bh.png' },
    { code: 'bd', dial: '+880', name: 'Bangladesh', flag: 'https://flagcdn.com/w20/bd.png' },
    { code: 'bb', dial: '+1', name: 'Barbados', flag: 'https://flagcdn.com/w20/bb.png' },
    { code: 'by', dial: '+375', name: 'Belarus', flag: 'https://flagcdn.com/w20/by.png' },
    { code: 'be', dial: '+32', name: 'Belgium', flag: 'https://flagcdn.com/w20/be.png' },
    { code: 'bz', dial: '+501', name: 'Belize', flag: 'https://flagcdn.com/w20/bz.png' },
    { code: 'bj', dial: '+229', name: 'Benin', flag: 'https://flagcdn.com/w20/bj.png' },
    { code: 'bt', dial: '+975', name: 'Bhutan', flag: 'https://flagcdn.com/w20/bt.png' },
    { code: 'bo', dial: '+591', name: 'Bolivia', flag: 'https://flagcdn.com/w20/bo.png' },
    { code: 'ba', dial: '+387', name: 'Bosnia and Herzegovina', flag: 'https://flagcdn.com/w20/ba.png' },
    { code: 'bw', dial: '+267', name: 'Botswana', flag: 'https://flagcdn.com/w20/bw.png' },
    { code: 'br', dial: '+55', name: 'Brazil', flag: 'https://flagcdn.com/w20/br.png' },
    { code: 'bn', dial: '+673', name: 'Brunei', flag: 'https://flagcdn.com/w20/bn.png' },
    { code: 'bg', dial: '+359', name: 'Bulgaria', flag: 'https://flagcdn.com/w20/bg.png' },
    { code: 'bf', dial: '+226', name: 'Burkina Faso', flag: 'https://flagcdn.com/w20/bf.png' },
    { code: 'bi', dial: '+257', name: 'Burundi', flag: 'https://flagcdn.com/w20/bi.png' },
    { code: 'cv', dial: '+238', name: 'Cabo Verde', flag: 'https://flagcdn.com/w20/cv.png' },
    { code: 'kh', dial: '+855', name: 'Cambodia', flag: 'https://flagcdn.com/w20/kh.png' },
    { code: 'cm', dial: '+237', name: 'Cameroon', flag: 'https://flagcdn.com/w20/cm.png' },
    { code: 'cf', dial: '+236', name: 'Central African Republic', flag: 'https://flagcdn.com/w20/cf.png' },
    { code: 'td', dial: '+235', name: 'Chad', flag: 'https://flagcdn.com/w20/td.png' },
    { code: 'cl', dial: '+56', name: 'Chile', flag: 'https://flagcdn.com/w20/cl.png' },
    { code: 'cn', dial: '+86', name: 'China', flag: 'https://flagcdn.com/w20/cn.png' },
    { code: 'co', dial: '+57', name: 'Colombia', flag: 'https://flagcdn.com/w20/co.png' },
    { code: 'km', dial: '+269', name: 'Comoros', flag: 'https://flagcdn.com/w20/km.png' },
    { code: 'cg', dial: '+242', name: 'Congo', flag: 'https://flagcdn.com/w20/cg.png' },
    { code: 'cr', dial: '+506', name: 'Costa Rica', flag: 'https://flagcdn.com/w20/cr.png' },
    { code: 'hr', dial: '+385', name: 'Croatia', flag: 'https://flagcdn.com/w20/hr.png' },
    { code: 'cu', dial: '+53', name: 'Cuba', flag: 'https://flagcdn.com/w20/cu.png' },
    { code: 'cy', dial: '+357', name: 'Cyprus', flag: 'https://flagcdn.com/w20/cy.png' },
    { code: 'cz', dial: '+420', name: 'Czechia', flag: 'https://flagcdn.com/w20/cz.png' },
    { code: 'dk', dial: '+45', name: 'Denmark', flag: 'https://flagcdn.com/w20/dk.png' },
    { code: 'dj', dial: '+253', name: 'Djibouti', flag: 'https://flagcdn.com/w20/dj.png' },
    { code: 'dm', dial: '+1', name: 'Dominica', flag: 'https://flagcdn.com/w20/dm.png' },
    { code: 'do', dial: '+1', name: 'Dominican Republic', flag: 'https://flagcdn.com/w20/do.png' },
    { code: 'ec', dial: '+593', name: 'Ecuador', flag: 'https://flagcdn.com/w20/ec.png' },
    { code: 'eg', dial: '+20', name: 'Egypt', flag: 'https://flagcdn.com/w20/eg.png' },
    { code: 'sv', dial: '+503', name: 'El Salvador', flag: 'https://flagcdn.com/w20/sv.png' },
    { code: 'gq', dial: '+240', name: 'Equatorial Guinea', flag: 'https://flagcdn.com/w20/gq.png' },
    { code: 'er', dial: '+291', name: 'Eritrea', flag: 'https://flagcdn.com/w20/er.png' },
    { code: 'ee', dial: '+372', name: 'Estonia', flag: 'https://flagcdn.com/w20/ee.png' },
    { code: 'sz', dial: '+268', name: 'Eswatini', flag: 'https://flagcdn.com/w20/sz.png' },
    { code: 'et', dial: '+251', name: 'Ethiopia', flag: 'https://flagcdn.com/w20/et.png' },
    { code: 'fj', dial: '+679', name: 'Fiji', flag: 'https://flagcdn.com/w20/fj.png' },
    { code: 'fi', dial: '+358', name: 'Finland', flag: 'https://flagcdn.com/w20/fi.png' },
    { code: 'fr', dial: '+33', name: 'France', flag: 'https://flagcdn.com/w20/fr.png' },
    { code: 'ga', dial: '+241', name: 'Gabon', flag: 'https://flagcdn.com/w20/ga.png' },
    { code: 'gm', dial: '+220', name: 'Gambia', flag: 'https://flagcdn.com/w20/gm.png' },
    { code: 'ge', dial: '+995', name: 'Georgia', flag: 'https://flagcdn.com/w20/ge.png' },
    { code: 'de', dial: '+49', name: 'Germany', flag: 'https://flagcdn.com/w20/de.png' },
    { code: 'gr', dial: '+30', name: 'Greece', flag: 'https://flagcdn.com/w20/gr.png' },
    { code: 'gd', dial: '+1', name: 'Grenada', flag: 'https://flagcdn.com/w20/gd.png' },
    { code: 'gt', dial: '+502', name: 'Guatemala', flag: 'https://flagcdn.com/w20/gt.png' },
    { code: 'gn', dial: '+224', name: 'Guinea', flag: 'https://flagcdn.com/w20/gn.png' },
    { code: 'gw', dial: '+245', name: 'Guinea-Bissau', flag: 'https://flagcdn.com/w20/gw.png' },
    { code: 'gy', dial: '+592', name: 'Guyana', flag: 'https://flagcdn.com/w20/gy.png' },
    { code: 'ht', dial: '+509', name: 'Haiti', flag: 'https://flagcdn.com/w20/ht.png' },
    { code: 'hn', dial: '+504', name: 'Honduras', flag: 'https://flagcdn.com/w20/hn.png' },
    { code: 'hu', dial: '+36', name: 'Hungary', flag: 'https://flagcdn.com/w20/hu.png' },
    { code: 'is', dial: '+354', name: 'Iceland', flag: 'https://flagcdn.com/w20/is.png' },
    { code: 'in', dial: '+91', name: 'India', flag: 'https://flagcdn.com/w20/in.png' },
    { code: 'id', dial: '+62', name: 'Indonesia', flag: 'https://flagcdn.com/w20/id.png' },
    { code: 'ir', dial: '+98', name: 'Iran', flag: 'https://flagcdn.com/w20/ir.png' },
    { code: 'iq', dial: '+964', name: 'Iraq', flag: 'https://flagcdn.com/w20/iq.png' },
    { code: 'ie', dial: '+353', name: 'Ireland', flag: 'https://flagcdn.com/w20/ie.png' },
    { code: 'il', dial: '+972', name: 'Israel', flag: 'https://flagcdn.com/w20/il.png' },
    { code: 'it', dial: '+39', name: 'Italy', flag: 'https://flagcdn.com/w20/it.png' },
    { code: 'jm', dial: '+1', name: 'Jamaica', flag: 'https://flagcdn.com/w20/jm.png' },
    { code: 'jp', dial: '+81', name: 'Japan', flag: 'https://flagcdn.com/w20/jp.png' },
    { code: 'jo', dial: '+962', name: 'Jordan', flag: 'https://flagcdn.com/w20/jo.png' },
    { code: 'kz', dial: '+7', name: 'Kazakhstan', flag: 'https://flagcdn.com/w20/kz.png' },
    { code: 'ki', dial: '+686', name: 'Kiribati', flag: 'https://flagcdn.com/w20/ki.png' },
    { code: 'kp', dial: '+850', name: 'North Korea', flag: 'https://flagcdn.com/w20/kp.png' },
    { code: 'kr', dial: '+82', name: 'South Korea', flag: 'https://flagcdn.com/w20/kr.png' },
    { code: 'kw', dial: '+965', name: 'Kuwait', flag: 'https://flagcdn.com/w20/kw.png' },
    { code: 'kg', dial: '+996', name: 'Kyrgyzstan', flag: 'https://flagcdn.com/w20/kg.png' },
    { code: 'la', dial: '+856', name: 'Laos', flag: 'https://flagcdn.com/w20/la.png' },
    { code: 'lv', dial: '+371', name: 'Latvia', flag: 'https://flagcdn.com/w20/lv.png' },
    { code: 'lb', dial: '+961', name: 'Lebanon', flag: 'https://flagcdn.com/w20/lb.png' },
    { code: 'ls', dial: '+266', name: 'Lesotho', flag: 'https://flagcdn.com/w20/ls.png' },
    { code: 'lr', dial: '+231', name: 'Liberia', flag: 'https://flagcdn.com/w20/lr.png' },
    { code: 'ly', dial: '+218', name: 'Libya', flag: 'https://flagcdn.com/w20/ly.png' },
    { code: 'li', dial: '+423', name: 'Liechtenstein', flag: 'https://flagcdn.com/w20/li.png' },
    { code: 'lt', dial: '+370', name: 'Lithuania', flag: 'https://flagcdn.com/w20/lt.png' },
    { code: 'lu', dial: '+352', name: 'Luxembourg', flag: 'https://flagcdn.com/w20/lu.png' },
    { code: 'mg', dial: '+261', name: 'Madagascar', flag: 'https://flagcdn.com/w20/mg.png' },
    { code: 'mw', dial: '+265', name: 'Malawi', flag: 'https://flagcdn.com/w20/mw.png' },
    { code: 'my', dial: '+60', name: 'Malaysia', flag: 'https://flagcdn.com/w20/my.png' },
    { code: 'mv', dial: '+960', name: 'Maldives', flag: 'https://flagcdn.com/w20/mv.png' },
    { code: 'ml', dial: '+223', name: 'Mali', flag: 'https://flagcdn.com/w20/ml.png' },
    { code: 'mt', dial: '+356', name: 'Malta', flag: 'https://flagcdn.com/w20/mt.png' },
    { code: 'mh', dial: '+692', name: 'Marshall Islands', flag: 'https://flagcdn.com/w20/mh.png' },
    { code: 'mr', dial: '+222', name: 'Mauritania', flag: 'https://flagcdn.com/w20/mr.png' },
    { code: 'mu', dial: '+230', name: 'Mauritius', flag: 'https://flagcdn.com/w20/mu.png' },
    { code: 'mx', dial: '+52', name: 'Mexico', flag: 'https://flagcdn.com/w20/mx.png' },
    { code: 'fm', dial: '+691', name: 'Micronesia', flag: 'https://flagcdn.com/w20/fm.png' },
    { code: 'md', dial: '+373', name: 'Moldova', flag: 'https://flagcdn.com/w20/md.png' },
    { code: 'mc', dial: '+377', name: 'Monaco', flag: 'https://flagcdn.com/w20/mc.png' },
    { code: 'mn', dial: '+976', name: 'Mongolia', flag: 'https://flagcdn.com/w20/mn.png' },
    { code: 'me', dial: '+382', name: 'Montenegro', flag: 'https://flagcdn.com/w20/me.png' },
    { code: 'ma', dial: '+212', name: 'Morocco', flag: 'https://flagcdn.com/w20/ma.png' },
    { code: 'mz', dial: '+258', name: 'Mozambique', flag: 'https://flagcdn.com/w20/mz.png' },
    { code: 'mm', dial: '+95', name: 'Myanmar', flag: 'https://flagcdn.com/w20/mm.png' },
    { code: 'na', dial: '+264', name: 'Namibia', flag: 'https://flagcdn.com/w20/na.png' },
    { code: 'nr', dial: '+674', name: 'Nauru', flag: 'https://flagcdn.com/w20/nr.png' },
    { code: 'np', dial: '+977', name: 'Nepal', flag: 'https://flagcdn.com/w20/np.png' },
    { code: 'nl', dial: '+31', name: 'Netherlands', flag: 'https://flagcdn.com/w20/nl.png' },
    { code: 'nz', dial: '+64', name: 'New Zealand', flag: 'https://flagcdn.com/w20/nz.png' },
    { code: 'ni', dial: '+505', name: 'Nicaragua', flag: 'https://flagcdn.com/w20/ni.png' },
    { code: 'ne', dial: '+227', name: 'Niger', flag: 'https://flagcdn.com/w20/ne.png' },
    { code: 'mk', dial: '+389', name: 'North Macedonia', flag: 'https://flagcdn.com/w20/mk.png' },
    { code: 'no', dial: '+47', name: 'Norway', flag: 'https://flagcdn.com/w20/no.png' },
    { code: 'om', dial: '+968', name: 'Oman', flag: 'https://flagcdn.com/w20/om.png' },
    { code: 'pk', dial: '+92', name: 'Pakistan', flag: 'https://flagcdn.com/w20/pk.png' },
    { code: 'pw', dial: '+680', name: 'Palau', flag: 'https://flagcdn.com/w20/pw.png' },
    { code: 'pa', dial: '+507', name: 'Panama', flag: 'https://flagcdn.com/w20/pa.png' },
    { code: 'pg', dial: '+675', name: 'Papua New Guinea', flag: 'https://flagcdn.com/w20/pg.png' },
    { code: 'py', dial: '+595', name: 'Paraguay', flag: 'https://flagcdn.com/w20/py.png' },
    { code: 'pe', dial: '+51', name: 'Peru', flag: 'https://flagcdn.com/w20/pe.png' },
    { code: 'ph', dial: '+63', name: 'Philippines', flag: 'https://flagcdn.com/w20/ph.png' },
    { code: 'pl', dial: '+48', name: 'Poland', flag: 'https://flagcdn.com/w20/pl.png' },
    { code: 'pt', dial: '+351', name: 'Portugal', flag: 'https://flagcdn.com/w20/pt.png' },
    { code: 'qa', dial: '+974', name: 'Qatar', flag: 'https://flagcdn.com/w20/qa.png' },
    { code: 'ro', dial: '+40', name: 'Romania', flag: 'https://flagcdn.com/w20/ro.png' },
    { code: 'ru', dial: '+7', name: 'Russia', flag: 'https://flagcdn.com/w20/ru.png' },
    { code: 'rw', dial: '+250', name: 'Rwanda', flag: 'https://flagcdn.com/w20/rw.png' },
    { code: 'kn', dial: '+1', name: 'Saint Kitts and Nevis', flag: 'https://flagcdn.com/w20/kn.png' },
    { code: 'lc', dial: '+1', name: 'Saint Lucia', flag: 'https://flagcdn.com/w20/lc.png' },
    { code: 'vc', dial: '+1', name: 'Saint Vincent', flag: 'https://flagcdn.com/w20/vc.png' },
    { code: 'ws', dial: '+685', name: 'Samoa', flag: 'https://flagcdn.com/w20/ws.png' },
    { code: 'sm', dial: '+378', name: 'San Marino', flag: 'https://flagcdn.com/w20/sm.png' },
    { code: 'st', dial: '+239', name: 'Sao Tome and Principe', flag: 'https://flagcdn.com/w20/st.png' },
    { code: 'sa', dial: '+966', name: 'Saudi Arabia', flag: 'https://flagcdn.com/w20/sa.png' },
    { code: 'sn', dial: '+221', name: 'Senegal', flag: 'https://flagcdn.com/w20/sn.png' },
    { code: 'rs', dial: '+381', name: 'Serbia', flag: 'https://flagcdn.com/w20/rs.png' },
    { code: 'sc', dial: '+248', name: 'Seychelles', flag: 'https://flagcdn.com/w20/sc.png' },
    { code: 'sl', dial: '+232', name: 'Sierra Leone', flag: 'https://flagcdn.com/w20/sl.png' },
    { code: 'sg', dial: '+65', name: 'Singapore', flag: 'https://flagcdn.com/w20/sg.png' },
    { code: 'sk', dial: '+421', name: 'Slovakia', flag: 'https://flagcdn.com/w20/sk.png' },
    { code: 'si', dial: '+386', name: 'Slovenia', flag: 'https://flagcdn.com/w20/si.png' },
    { code: 'sb', dial: '+677', name: 'Solomon Islands', flag: 'https://flagcdn.com/w20/sb.png' },
    { code: 'so', dial: '+252', name: 'Somalia', flag: 'https://flagcdn.com/w20/so.png' },
    { code: 'es', dial: '+34', name: 'Spain', flag: 'https://flagcdn.com/w20/es.png' },
    { code: 'lk', dial: '+94', name: 'Sri Lanka', flag: 'https://flagcdn.com/w20/lk.png' },
    { code: 'sd', dial: '+249', name: 'Sudan', flag: 'https://flagcdn.com/w20/sd.png' },
    { code: 'sr', dial: '+597', name: 'Suriname', flag: 'https://flagcdn.com/w20/sr.png' },
    { code: 'se', dial: '+46', name: 'Sweden', flag: 'https://flagcdn.com/w20/se.png' },
    { code: 'ch', dial: '+41', name: 'Switzerland', flag: 'https://flagcdn.com/w20/ch.png' },
    { code: 'sy', dial: '+963', name: 'Syria', flag: 'https://flagcdn.com/w20/sy.png' },
    { code: 'tj', dial: '+992', name: 'Tajikistan', flag: 'https://flagcdn.com/w20/tj.png' },
    { code: 'tz', dial: '+255', name: 'Tanzania', flag: 'https://flagcdn.com/w20/tz.png' },
    { code: 'th', dial: '+66', name: 'Thailand', flag: 'https://flagcdn.com/w20/th.png' },
    { code: 'tl', dial: '+670', name: 'Timor-Leste', flag: 'https://flagcdn.com/w20/tl.png' },
    { code: 'tg', dial: '+228', name: 'Togo', flag: 'https://flagcdn.com/w20/tg.png' },
    { code: 'to', dial: '+676', name: 'Tonga', flag: 'https://flagcdn.com/w20/to.png' },
    { code: 'tt', dial: '+1', name: 'Trinidad and Tobago', flag: 'https://flagcdn.com/w20/tt.png' },
    { code: 'tn', dial: '+216', name: 'Tunisia', flag: 'https://flagcdn.com/w20/tn.png' },
    { code: 'tr', dial: '+90', name: 'Turkey', flag: 'https://flagcdn.com/w20/tr.png' },
    { code: 'tm', dial: '+993', name: 'Turkmenistan', flag: 'https://flagcdn.com/w20/tm.png' },
    { code: 'tv', dial: '+688', name: 'Tuvalu', flag: 'https://flagcdn.com/w20/tv.png' },
    { code: 'ug', dial: '+256', name: 'Uganda', flag: 'https://flagcdn.com/w20/ug.png' },
    { code: 'ua', dial: '+380', name: 'Ukraine', flag: 'https://flagcdn.com/w20/ua.png' },
    { code: 'ae', dial: '+971', name: 'United Arab Emirates', flag: 'https://flagcdn.com/w20/ae.png' },
    { code: 'uy', dial: '+598', name: 'Uruguay', flag: 'https://flagcdn.com/w20/uy.png' },
    { code: 'uz', dial: '+998', name: 'Uzbekistan', flag: 'https://flagcdn.com/w20/uz.png' },
    { code: 'vu', dial: '+678', name: 'Vanuatu', flag: 'https://flagcdn.com/w20/vu.png' },
    { code: 've', dial: '+58', name: 'Venezuela', flag: 'https://flagcdn.com/w20/ve.png' },
    { code: 'vn', dial: '+84', name: 'Vietnam', flag: 'https://flagcdn.com/w20/vn.png' },
    { code: 'ye', dial: '+967', name: 'Yemen', flag: 'https://flagcdn.com/w20/ye.png' },
    { code: 'zm', dial: '+260', name: 'Zambia', flag: 'https://flagcdn.com/w20/zm.png' },
    { code: 'zw', dial: '+263', name: 'Zimbabwe', flag: 'https://flagcdn.com/w20/zw.png' },
];
